title: Zecheng Zhou
description: 个人主页与学习笔记
theme: just-the-docs

url: https://pku-zhou.github.io

# 所有页面默认采用default布局
defaults:
  - scope:
      path: ""
    values:
      layout: default

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template

